version: '3.8'

services:
  openspeech:
    image: ghcr.io/binuengoor/openspeech:latest
    container_name: openspeech
    ports:
      - "3000:3000"
    volumes:
      # Persist settings
      - ./data:/app/data
      # Persist generated audio files
      - ./output:/app/output
    environment:
      - NODE_ENV=production
    restart: unless-stopped
